### ISSUE TITLE
Virginia

### ISSUE THREAD

**Issue by bezanas** [covid-db/covid-scrapers#21]
cases reported 1020
http://www.vdh.virginia.gov/

from county cases
http://www.vdh.virginia.gov/coronavirus/
more specific 
https://public.tableau.com/shared/CDSX4BH9Q?:display_count=n&:origin=viz_share_link&:embed=y

**Comment by prikhi** [comment]
Dupe, #16 ?

**Comment by mightybyte** [comment]
Yeah, we were trying to organize the issues and prioritize in the roadmap project.  Thanks for the heads-up.  I'll copy the extra information here over to the other one.
